### ISSUE TITLE
[3] "other" index gone, fluentd not logging the error

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1084]
**Describe the bug**
Recently in a cluster all indices for the `other` alias was gone. This meant that fluentd could not push those logs to opensearch. Fluentd was then slowly building up a buffer of logs and started to use a lot more cpu. When checking the logs of fluentd it was not saying anything, although when switching to `debug` logging it said `[opensearch] Indexed (op = index), 30 index_not_found_exception`. 

I don't know why the `other` indices were gone. But I suspect that it at some point failed to rollover the index (and continued to do so). Then it eventually got deleted once the retention time was up for the index. 

The problem was solved by rerunning the `configurer` job to recreate the missing index. `./bin/ck8s ops helmfile sc -l app=opensearch-configurer sync`

**To Reproduce**
Not sure how to reproduce the steps that lead to the `other` idices being missing. But you could manually simulatee that to see the later issues by:
1. Log in to opensearch
2. Delete all indices for `other`
3. See that opensearch starts to use more resources and build up a buffer of logs. Also see that it does not log anything useful (without switching to debug logging).

**Expected behavior**
- The last index for an alias should never be deleted, regardless of how it happened for me this time.
- If an index is missing, fluentd should clearly log an error to inform about it. Including what index is missing.

**Screenshots**
![fluentd-cpu](https://user-images.githubusercontent.com/58632240/179459340-9ccffcef-0eaa-487d-9834-037ec858b369.png)
![fluentd-metrics](https://user-images.githubusercontent.com/58632240/179459347-837b1e5c-44b7-455d-894c-b2b76ccb2e65.png)

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.22.0

**Additional context**

**Comment by robinelastisys** [comment]
The issue itself has turned out to be something totally different from what we started out trying to solve and we have now decided to create a new issue to solve what's wrong in "fluentd" rather than in OpenSearch and its Indices handling. Why?:

By default, OpenSearch creates one default write index for each default alias we have (kubeaudit, kubernetes, authlog, other). If fluentd-plugin-opensearch or fluentd-plugin-elasticsearch cant find this default index(in the alias), it tries to create a new index.

**The big problem**: The new index fluentd creates cannot be set to be the main write index as the default index is the main one already no matter if our fluentd setup can find it or not(their cannot be 2 at the same time).

**End conclusion & solution**: Re-configure fluentd to find the default write index in each alias in the first place instead of trying to create a new one when it cannot be found.
