### ISSUE TITLE
[3] Users elasticsearch dashboard in grafana shows errors and no data

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#12]
The elasticsearch dashboard in the user grafana is empty and shows errors about the datasource. I think this dashboard should not be available to the user. It should only be in the Ops grafana.

**Comment by tordsson** [comment]
Affects other dashboards as well

**Comment by crssnd** [comment]
I am thinking to move the user-grafana from the service cluster to the workload cluster, in order to separate the ops dashboards from the user dashboards. 
Is this something that we want to rediscuss?

I am not sure if this is question for @pettersv, @tordsson or @cristiklein

**Comment by cristiklein** [comment]
@crssnd I'm unsure it would be a good idea to move user Grafana to the workload cluster. Currently, we have both Grafanas (Grafanae?) in the service cluster, since some customers have asked us for supporting multiple workload clusters with a single service cluster. I'm not sure this feature is still interesting, but moving user Grafana to the workload_cluster would make this somewhat odd. "Odd" in the sense that either one workload_cluster would be "sanctioned" to host the user Grafana (which gives access to all other workload_cluster monitoring data), or each workload_cluster would host their own user Grafana (which again gives access to all other workload_cluster monitoring data). In either case, InfluxDB would still be in the service_cluster, so I don't see the value of the added link, i.e., non-logging view-only InfluxDB connection from the workload_cluster to the service_cluster.

So technically possible, but architecturally odd. :smile:

Do you see any pros in moving user Grafana to the workload_cluster?

Regarding the original issue text, I think we should not hide anything from the user. If we monitor Elasticsearch, they should be able to see that too. They entrust us with their data, not we protect our platform from their malice. :smile: @tordsson Any PM opinion here?

**Comment by crssnd** [comment]
some pros:
- separate the dashboards and allow the user to add new dashboards that we do not want to maintain;
- install grafana using kube-prometheus-stack helm chart (used on sc) instead of using a separate helm chart only for grafana

If indeed we do not want to hide anything that will solve this issue and #223 (although restricting their access in a unified Grafana needs more investigation).

**Comment by crssnd** [comment]
we have implemented a solution to choose what ops dashboards to show to the users.

**Comment by cristiklein** [comment]
Subject to approval from @tordsson and @pettersv , we should aim for transparency towards our users and give them access to Elasticsearch metrics.

@crssnd Do I need to create a new issue or can the present issue be resolved -- given this new direction -- within the allocated time budget?

**Comment by crssnd** [comment]
@cristiklein no need for a new issue. I can solve it within the allocated time budget, if approved.

**Comment by tordsson** [comment]
Ok with me to expose these metrics + show customers that we monitor ElasticSearch, we have nothing to hide...

**Comment by crssnd** [comment]
@tordsson (just to clarify) they will have access to all service cluster metrics, not just for elasticsearch
I added the option for us to decide, if we want to make a certain ops Grafana dashboard visible to the user or not (elasticsearch dashboard will be visible by default)
