### ISSUE TITLE
[5] Add support for Azure blob storage

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#132]
To support cluster fully in azure, we need to add support for blob storage

This includes:
* Modifying the backup scripts to work with azure
* Elasticsearch
* Harbor
* Velero
* *Probably something else*

## Acceptance criteria

* Create a cluster with `objectStorage.type` set to `abs` *(or something like that)*

**Comment by Xartos** [comment]
We should consider using minio as "proxy" for all these kinds of object storage.
Then these tasks would only be to add the correct configuration for minio to work with azure and all the other stuff would just work.

**Comment by tordsson** [comment]
Previous comments (from deprecated ck8s-cluster issue on the same topic): 

At the moment we don't support azure object storage (since it does not speak s3 directly)
We should investigate how we should implement support for this for all our services.

One solution would be to use minio to proxy the traffic https://cloudblogs.microsoft.com/opensource/2017/11/09/s3cmd-amazon-s3-compatible-apps-azure-storage/

**Comment by OlleLarsson** [comment]
Well can minio act as a gatway for other cloud provider's object storage solutions?
I don't seen any mention of GCS in the [gateways docs](https://docs.min.io/docs/minio-gateway-for-azure.html) at least.

**Comment by OlleLarsson** [comment]
@cristiklein and @tordsson close?

**Comment by cristiklein** [comment]
@tordsson I recommend closing it for now, given the cloud providers that we focus on.
