### ISSUE TITLE
[5] Try to use Gatekeeper to replace PSP

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#1324]
**What should be investigated.**
What technology/product/concept should be investigated?

Take a look [here](https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy) and try to setup these policies to act as a replacement for PSPs

Since we think that the default PSA given from kubernetes is too limited we want to know if this solution is more similar to how PSP works as of now.

**What artifacts should this produce.**
How should the knowledge gathered from this task be captured.

* Investigation doc describing how to setup these policies and how they differ from the default PSA and the current PSP.

**Comment by raviranjanelastisys** [comment]
Please find the attached the Detailed investigation file for reference - https://docs.google.com/spreadsheets/d/1u0bZ2BzrlHM1VAkN5E-eTI__uHHn2AfnVLxhrUtqvws/edit?usp=sharing

![image](https://user-images.githubusercontent.com/75951259/214763715-93efbd77-eead-4956-81a4-1c73034db651.png)


So based on investigations , i would conclude below points.

1. We can achieve all the `PSP's-restricted` with Gatekeeper-PSP-polcies. Gatekeeper can today already do everything that PSPs can do and more.
2. Since we are already using the Gatekeeper policy in our environment , so installtion of gatekeeper is not needed as already done.
3. We can add the exemption to the container via `exemptImages` instead `namespaces` but not possible to all the Gatekeeper-PSP-policy as said above.Any container that uses an image that matches an entry in this list will be excluded from enforcement.
4. In few policy , we might have to give the `namespace` exemptions instead `exemptImages` . Ideally this is the case when the `constrainttemplate` policy violations is defined based of not containers input. Ex- https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-namespaces/template.yaml#L38
5. We need to identify all the images to whitelist including AMS's and accordingly rollout if decided.
6. It also does not involve RBAC and avoids the first policy in alphabetical order that you have access to situation but instead is scoped to either the whole cluster, a list of namespaces to enforce against, or a list of namespaces to exclude or the list of containers to exclude.

**Comment by raviranjanelastisys** [comment]
Investigation docs PR opened - https://github.com/elastisys/ck8s-ops/pull/3417

**Comment by raviranjanelastisys** [comment]
Closing as PR is Merged now !!
