### ISSUE TITLE
[1] user-admin-cluster-wide-delegation doesn't work

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1393]
**Describe the bug**
According to the public docs the admin user should be able to add other admin users, see https://elastisys.io/compliantkubernetes/user-guide/delegation/#add-a-user-admin

First of all the admin user is not allowed to edit the `user-admin-cluster-wide-delegation` ClusterRoleBinding, and even if they could edit it, when adding subjects to the ClusterRolebinding `user-admin-cluster-wide-delegation` the subject doesn't actually become an admin.

**To Reproduce**
1. Go to [the clusterrole](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/user-rbac/templates/clusterroles/user-admin-cluster-wide-delegation.yaml)
2. Note that it only gives access to the [extra-user-view](https://github.com/elastisys/compliantkubernetes-apps/blob/main/manifests/user-rbac/clusterrolebindings/extra-user-view.yaml) ClusterRolebinding (which is also probably located in the wrong place)
3. Note that it only references the [user-view](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/user-rbac/templates/clusterroles/user-view.yaml) Clusterrole, which does not make the new subject an admin.

**Expected behavior**
The subject should become bound to the `admin` ClusterRole, similarly to our `workload-admin` rolebindings that get added in each customer namespace. The user admins should be able to do this.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version `v0.21+`

**Comment by ayoubeddafali** [comment]
@davidumea  I think I have figured it out. I believe the confusion comes from the public docs.
Instead of editing the `user-admin-cluster-wide-delegation` **CRB**, the user admins configured in the wc-config.yml should edit the `extra-user-view` **CRB**, which they should be able to do thanks to [user-admin-cluster-wide-delegation](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/user-rbac/templates/clusterrolebindings/user-admin-cluster-wide-delegation.yaml) **CRB**, by adding the adequate subjects ( user, groups .. ). Once it's done, the subjects will have the `user-view` Cluster Role, and they should be admins then.

**Comment by ayoubeddafali** [comment]
@raviranjanelastisys @davidumea @viktor-f what do you think ?

**Comment by davidumea** [comment]
Yes looks good, I guess the tricky part is that this extra-workload-admin **RB** has to be created by helm to begin with but not be overwritten/reverted once you apply wc.

Then I guess the admin user would need to add the new subject to both the `extra-user-view` **CRB** and this new `extra-workload-admin` **RB**, as some of the permissions in the [user-view](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/user-rbac/templates/clusterroles/user-view.yaml) **CR** are not in the admin **CR**.
