### ISSUE TITLE
Allow admin users to label "regular" worker nodes safely

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1595]
**Is your feature request related to a problem? Please describe.**
As an admin user I want to label my worker nodes in order to set up nodeAffinity.

To allow this, the cluster admin has to give the admin users permissions to "patch" and "update" the specific nodes. We should allow this by default and then create some gatekeeper rules to make sure that the admin users can not do any other changes to the nodes, e.g. taint them. The admin user should only be allowed to label the worker nodes.

**Describe the solution you'd like**
Allow admin users to "patch" and "label" worker nodes.
Create Gatekeeper rules so the admin users can **only** label the **worker** nodes. (Make sure this doesn't stop them from being able to read all nodes)
These gatekeeper rules need to have an exception for master nodes and other worker nodes that the cluster admin may add, e.g. dedicated database nodes. The user admin should not be able to touch these nodes at all, only read access.

**Definition of done:**
User admins can now label their worker nodes safely by default, without being able to taint and otherwise "mess" with the nodes.

**Comment by viktor-f** [comment]
When moving to cluster api this does not feel like something that we want to support, since nodes will be recreated more often and users should not rely on labels staying if they add it to individual nodes.
Instead the users should tell their platform admins to add labels to the node groups that create nodes, that way they will be added to new nodes as well.

So I will close this issue, if you think that this is still needed for some other reason, then contact me.
