### ISSUE TITLE
[3] Investigate: CIS benchmark status in Compliance dashboard

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#182]
Please investigate if it's possible to have CIS benchmark results (as output by kube-bench) in the Compliance dashboard.

**Comment by tordsson** [comment]
If possible, document passed and failed tests for default ck8s setup

**Comment by cristiklein** [comment]
As an overarching requirement for dashboards, they should not only highlight issues, but also make it quick to figure out how to solve the issues.

The "capacity management" dashboard is a very telling example. It shows "79 containers are missing resource requests", then, just one click away, lists the Pods which are missing requests.

**Comment by viktor-f** [comment]
Results of investigation:
I found a project (https://github.com/ibrokethecloud/kube-bench-metrics) that had wrapped kube-bench to run once per hour on each node and also to expose metrics from those runs. It also included a simple grafana dashboard to show the metrics.
The project was rather outdated (used an old version of kube-bench) but I managed to update it and run it on a cluster. I also updated the dashboard a bit (see pictures below).

Dashboard showing results from a master node:
![kube-bench-master](https://user-images.githubusercontent.com/58632240/109946007-15798e00-7cd8-11eb-90a7-0ac954a2db25.png)
Results from a worker node:
![kube-bench-worker](https://user-images.githubusercontent.com/58632240/109946014-17435180-7cd8-11eb-8a70-088c86155067.png)

Things left to do:

1. The biggest thing is to figure out how we should handle `kube-bench-metrics`. I see four options:
a. Fork the project and maintain it ourself. The benefit is that we will have full control but we won't get any help maintaining it and others will probablt not benefit from it (since it will be harder to find the fork).
b. Try to upstream the changes. The original project has not been updated in a long while (with the exception of a licens that we recently asked for). So my guess is that the changes will probably be accepted but we won't really get any help in maintaining it. Benefit here is that it might be easier for others to also use this, but it might be harder to maintain.
c. Ask the owners to donate the project to us. The benefits here is that it will be as easy to maintain as a fork, but easier to find for others.
d. Skip this entirely if we don't think it's worth the effort to maintain it. Then I think we will have to scrap this whole dashboard.

2. We also need to ensure that the image is hosted somewhere and that the helmchart is available (here I suggest that we let the code stay in the repo for `kube-bench-metrics` but we upload it to elastisys chart-repo https://github.com/elastisys/chart-repo)
3. Add the dashboard to our dashboard chart in apps.

I'd like some input on number one before moving further on this.

**Comment by cristiklein** [comment]
@viktor-f Please go for 1b and if the author lost interest we can consider other options.

**Comment by cristiklein** [comment]
Also, nice dashboards!!! :smile:

**Comment by viktor-f** [comment]
The maintainer has said they can continue to maintain it. A PR is up for this now https://github.com/ibrokethecloud/kube-bench-metrics/pull/3

**Comment by viktor-f** [comment]
Three new follow-up issues are now created:
https://github.com/elastisys/compliantkubernetes-apps/issues/352
https://github.com/elastisys/compliantkubernetes-apps/issues/353
https://github.com/elastisys/compliantkubernetes-apps/issues/354
