### ISSUE TITLE
Improve resilience of applications

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#198]
To run ck8s in scenarios with high uptime requirements and (minimal disruptions) we should make the applications more resilient by making use of the tools that kubernetes provides us with. There are a lot of low hanging fruits here: resource requests/limits, multiple replicas, etc.
This issue is an epic to highlight this and help collecting relevant issues.

Sub issues/tasks:
- [Resource requests](https://github.com/elastisys/ck8s/issues/580)
- Multiple replicas: Most applications in ck8s run with a single replica, which makes them extremely sensitive to any disruptions. Most stateless applications could easily be scaled and spread over more nodes. For stateful applications, this may be hard to achieve, but we should look into what is possible. For example, some applications may benefit from a RWX volume that can be shared by multiple pods. This could apply to for example grafana.
- PodDisruptionBudgets and rollout strategy: Even cheaper than multiple replicas but with great impact on voulentary evictions or upgrades. Make sure that there is always another ready replica that can handle requests before we evict one.
- (Anti)Affinity: Spread pods over multiple nodes in order to tolerate node failure.
- Priority classes: There is not much point in having access to grafana if influxdb and prometheus are down. We need priority classes to tell kubernetes what applications should be prioritized above other.
- Limit ranges: To protect "system" applications in the workload cluster, we could use limit ranges to confine user namespaces to certain resource limits.
- For operations, HA alert manager, see https://github.com/elastisys/ck8s-ops/issues/69
- [Reserve system resources](https://github.com/elastisys/compliantkubernetes-kubespray/issues/15).

**Comment by cristiklein** [comment]
This epic was moved to low-priority for the following reasons:

- We have a few 8/5 opportunities in the pipeline, which would make 100% uptime pretty easy to achieve.
- For existing customers, the underlying cloud provider is the "bottleneck" for uptime.
- We must ensure that we have a proper maintenance window (which is excluded from uptime measurement). Good engineering should not substitute reasonable contracts.
- Without a clear problem to solve, this epic is likely to end up in over-engineering.

However, the two issues referenced in the epic (resource requests and reserve capacity for system daemons) are high-prio.

This epic will be prioritized when it can be linked to a problem. The problem should preferably be quantified, so that we can set improvement targets of this epic and measure improvements as a results of completing this epic.
