### ISSUE TITLE
Produce "lighter" renderings of Compliant Kubernetes

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#206]
**Is your feature request related to a problem? Please describe.**

We start to realize that some of our customers like Compliant Kubernetes, but might reject it due to the overhead it imposes in terms of infrastructure cost. We need to support "lighter" renderings, such as:

1. 8/5 uptime, i.e., single master, no spare capacity, single cluster (both service "cluster" and workload "cluster" runs on a single Kubernetes cluster)
2. Each component can be disabled, e.g., no Elasticsearch.

**Describe the solution you'd like**

I'm brainstorming here:
1. Helmfile only has one environment.
2. `ck8s init` may produce a few flavors:
    1. Single-cluster, produces `~/.ck8s/aws/cluster_name.yaml` and `~/.ck8s/aws/secrets.yaml`.
    2. Multi-cluster, produces `~/.ck8s/aws/sc.yaml`, `~/.ck8s/aws/wc.yaml` and `~/.ck8s/aws/secrets.yaml`.
3. `ck8s apply` is as light as:
    ```
    for CLUSTER in $CLUSTERS; do
      helmfile --context $CLUSTER --values ~/.ck8s/aws/$CLUSTER.yaml apply
    done
    ```

**Describe alternatives you've considered**

I didn't. I'm brainstorming. :smile: 

**Additional context**

Currently, a full Compliant Kubernetes setup adds (on top of application requirements):
1. 3x masters for the service cluster
2. 3x masters for the workload cluster
3. 3x-ish workers for Elasticsearch
4. 1x-ish workers for workload cluster components
5. 1x-ish workers for service cluster components

If you want to start with an application needing 2 CPUs and 8 GB of RAM, the above overhead can be quite discouraging.

**Definition of done:**

We have an architectural decision and actionable issues on how to support the above feature.

**Subtasks**

- [x] Investigate single cluster setup https://github.com/elastisys/compliantkubernetes-apps/issues/293

**Comment by OlleLarsson** [comment]
Slightly releated: https://github.com/elastisys/compliantkubernetes-apps/issues/164

**Comment by lentzi90** [comment]
Some notes from my investigation into this.

- We can easily use complientkubernetes-kubespray to set up a single-node "cluster" with "extra nothing" (i.e. skip apps completely). We may want to set the minimum replicas to 1 for CoreDNS then since there will be 1 pending otherwise. I found no option to disable the DNS autoscaler btw, so this has to be removed manually if we don't want it.
- Some apps can already today be added one by one if we skip `ck8s apply` and do `ck8s ops helmfile sc -l key=value apply` instead. However, we obviously need more flexibility to be able to pick and choose freely. One thing that I'm wondering about specifically is if each of the options should also have dev/prod option? Does it make sense to offer a production flavor of a single cluster or even all-in-one single node cluster? If not, what kind of stability should we strive to for these flavors?
- The part about a single helmfile environment does not make sense to me. What is the meaning of it? Basically instead of using the environment variable to decide on what to install where, we would then have everything specified in the values? Today we have logic like `if environment == service_cluster: install elasticsearch`. If we skip it, how would we achieve the same thing? Separate helmfiles? An umbrella chart so we can set `enabled: true|false` in the values instead?

**Comment by cristiklein** [comment]
Continuing brainstorming:

1. Regarding DNS autoscaler, I'm unsure what you mean. Shouldn't `dns_min_replicas: 1` do the trick? ([set here](dns_min_replicas), [used here](https://github.com/kubernetes-sigs/kubespray/blob/0cc17267811efa7b9568cdd264d57fd1640e23a8/roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2#L81))
2. Good question. :) I'll ponder about it.
3. "Basically instead of using the environment variable to decide on what to install where, we would then have everything specified in the values?" Exactly!

So for an SC+WC pair, you would have (I am making things up):

```
# sc-config.yaml
elasticsearch:
  enabled: true
    
# wc0-config.yaml
elasticsearch:
  enabled: false
fluentd:
  forward-logs-to: elasticsearch.sc0.example.com
```

For a light rendering you would have:

```
# scwc-config.yaml
elasticsearch:
  enabled: true
fluentd:
  forward-logs-to: elasticsearch # i.e., via cluster DNS
```

**Comment by lentzi90** [comment]
Thanks for the quick response!

1. So the min replicas work as expected and gives me a single CoreDNS Pod, but there is also a DNS autoscaler Pod. It doesn't do any harm and it could be useful if we later decide to scale the cluster to many Nodes, but if we want minimal clusters I think it makes sense to remove it since it is just sitting there wasting resources. :smile: 
2. (just to make markdown happy and actually get number 3 below)
3. I'm a bit skeptical. What do we gain from this? It seems like a lot of work for pretty much the same functionality that we already have. :thinking:
   What I mean is that you cannot disable a chart without using an umbrella chart. This is not possible:
   ```
   # Install the chart, but also don't do it?
   helm upgrade --install elasticsearch charts/elasticsearch --set enabled=false
   ```
   So we would need to create an umbrella chart that we use for enabling/disabling what we want. This also means that we would need to specify all values relative to the subcharts which can be confusing.

**Comment by viktor-f** [comment]
3.
Helmfile has this functionallity and it's something we use already. Here's an example in our helmfile: https://github.com/elastisys/compliantkubernetes-apps/blob/544f7996e956426b456a20610a784a2d4d08f5d5/helmfile/01-applications.yaml#L305
That controls if harbor should be installed or not and it's based on our sc-config.

Though I'm not sure if it's good to use only this instead of the environments or not. But it feels like it should be pretty ok.

**Comment by lentzi90** [comment]
Is this still relevant?
One investigation task has been done and shows a possible way to implement this. Should we add an "evaluate" issue that we then can base a decision on? I guess another question is if we want to have this light rendering as a separate project or if all of ck8s should move in this direction where it is *possible* to set it up in a "light" way.
@cristiklein ?

**Comment by tordsson** [comment]
Please add such an evaluation issue @lentzi90.
I closing this issue now, we may revisit this topic in the future. Thanks everyone for your contributions!
