### ISSUE TITLE
[5] Investigate GitOps operators and de-Helmfile-ification

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#228]
**What should be investigated.**

Using a GitOps operator (e.g., [Flux v2](https://toolkit.fluxcd.io/)) to set up and operate Compliant Kubernetes components inside a workload cluster, in particular:

* Ingress-nginx
* Cert-manager
* Fluentd
* Prometheus
* Falco

The investigation should aim for something:

* Flexible: Components can be enabled/disable independently and configured as much as the underlying Helm Charts allow.
* Reliable: It just works (most of the time :smile:). When it fails, it clearly tells you why it failed and how to fix it.
* Un-astonishing: It works pretty much as a human would perform things manually. It does not take decisions a human operator wouldn't expect.

**What artifacts should this produce.**

* A tutorial
* A (video) demo

**Comment by OlleLarsson** [comment]
Can you clarify what you mean with _de-helmfile-ification_?
I am not sure I understand what issues helmfile introduces, it does not force you to use templating or any other fancy stuff.
I simply see helmfile as a nice way to organize helm releases and repositories.

**Comment by cristiklein** [comment]
Let me see if my logic holds.

There are calls for embracing GitOps. There are currently two contenders in this space: ArgoCD and FluxCD. FluxCD has a bit of a lead, based on the [CNCF End User Technology Radar](https://radar.cncf.io/2020-06-continuous-delivery). FluxCD seems to promote [similar concepts to helmfile](https://toolkit.fluxcd.io/components/helm/controller/). Hence, it does not make sense to use both FluxCD and Helmfile.

Now, whether we should stick to Helmfile (with push from a CI/CD pipeline) or should migrate to FluxCD, I don't really know. This task is about finding out. :smile:

One things that Flux has that I didn't see in Helmfile is [automatic image upgrading](https://toolkit.fluxcd.io/components/image/controller/). Is there any other feature that Flux offers and we would end up building around Helmfile? Are these extra features enough to make the switch? Stay tuned! :smile:

**Comment by lentzi90** [comment]
I wasn't aware of this issue until now. Looking forward to it!
Anyway, I think I have something that may be useful to whoever picks up this task (or maybe it can even close it?).
See the [flux branch in simple-ck8s](https://github.com/elastisys/simple-ck8s/tree/flux).
There are some thoughts at the bottom of the readme in the `flux` folder.

My main takeaways as an ArgoCD user:
- The visibility is rather poor. Even with the [Grafana dashboard](https://toolkit.fluxcd.io/guides/monitoring/#grafana-dashboards) you don't get more than a synced: `true`/`false`. No diffs or health status. I frequently found myself wondering "if it worked" or "where the problem was".
- Helm charts are better supported and it is nice to be able to use ConfigMaps and Secrets as values.
- Flux v2 "sprawls": need to check for HelmRelease and Kustomizations throughout all namespaces to know what you have in the cluster. Also, there are confusingly enough [2 kustomization types](https://toolkit.fluxcd.io/faq/#are-there-two-kustomization-types) :see_no_evil:
  - ArgoCD feels "cleaner": everything is handled as manifests, you just generate them in different ways.
- Encrypted secrets sucks. :cry: 
  It sounded very promising at first, with [built in support for SOPS](https://toolkit.fluxcd.io/guides/mozilla-sops/), but the reality feels awkward. Secrets are first generated manually (e.g. `kubectl create secret ...`), then encrypted.
  - The resulting "Secrets" are not valid Kubernetes objects and cannot be applied in the cluster by the user.
  - There is no simple way of editing the secrets unless you put everything in `stringData` instead of `data`.
  - All the secret data has to be stored inline in the encrypted secret (i.e. you cannot use kustomize to generate the secrets from files like [commonly done for ConfigMaps used as helm values](https://toolkit.fluxcd.io/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize)).

**Comment by cristiklein** [comment]
@OlleLarsson Given our move to Tekton, I'd say this is no longer relevant. Good to close from my side!
