### ISSUE TITLE
[2] Switch to ClusterIssuers

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#287]
**What should be investigated.**

Are new service cluster looks as follows:

```
$ kubectl get issuers,clusterissuers -o wide -A
NAMESPACE             NAME                                              READY   STATUS                                                 AGE
elastic-system        issuer.cert-manager.io/letsencrypt-prod           True    The ACME account was registered with the ACME server   4m2s
elastic-system        issuer.cert-manager.io/letsencrypt-staging        True    The ACME account was registered with the ACME server   4m2s
elastic-system        issuer.cert-manager.io/opendistro-es-ca           True    Signing CA verified                                    4m
elastic-system        issuer.cert-manager.io/opendistro-es-selfsigned   True                                                           4m
influxdb-prometheus   issuer.cert-manager.io/letsencrypt-prod           True    The ACME account was registered with the ACME server   4m2s
influxdb-prometheus   issuer.cert-manager.io/letsencrypt-staging        True    The ACME account was registered with the ACME server   4m2s
kube-system           issuer.cert-manager.io/letsencrypt-staging        True    The ACME account was registered with the ACME server   4m2s
monitoring            issuer.cert-manager.io/letsencrypt-staging        True    The ACME account was registered with the ACME server   4m2s
```

This feels fragile and wasteful. Can we use two ClusterIssuers instead, `letsencrypt-prod` and `letsencrypt-staging`?

**What artifacts should this produce.**

* A working demo with ClusterIssuers or a reason why this is a bad idea.

**Comment by lentzi90** [comment]
I agree we should switch to ClusterIssuers for SC. :+1: This is also [recommended by Let's encrypt](https://letsencrypt.org/docs/integration-guide/#one-account-or-many).

For WC I'm a bit doubtful, but we [don't really need any Issuers there](https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/wc-config.yaml#L388) now unless I'm missing something. The reason WC is special is because users would be able to use the ClusterIssuers there, which could be a problem if they violate it and run into rate limits. This is actually the reason we switched from ClusterIssuers to Issuers a long time ago. :grin: 
But as mentioned, we don't really need any issuers in WC so I guess the question is mute.

**Comment by cristiklein** [comment]
Well, we advocate best-practice configuration, so I think we should have ClusterIssuers in the WC too.

**Comment by lentzi90** [comment]
I think you misunderstand me. We don't currently have any Issuers or ClusterIssuers in WC so I think we can keep it that way.
However, if we ever find that we need, I think they should be Issuers in namespaces that the user doesn't have access to. Otherwise the user will be able to request certificates using this ClusterIssuer which could cause rate limits *for the admin/operator*.

**Comment by cristiklein** [comment]
Thanks for clarifying. I was operating under the assumption that we should install ClusterIssuers in the WC *for the user*. This would help us stick to our promise of "best practice configuration". My understanding is LetsEncrypt performs [rate limiting per registered domain](https://letsencrypt.org/docs/rate-limits/), so it does not really add any risk to the operator.

Let me go deeper into this point. I see two cases:
1. A registered domain points to the WC: Then the user can fiddle around and create/destroy Ingresses and trigger rate limiting. Whether we provide a ClusterIssuer or the user creates an Issuer makes no difference.
2. A registered domain does not point to the WC: Then the user cannot trigger rate limiting for it.

I think what I'm saying is to be mindful about pointing our registered domains *only* to the SC, and pointing either user-provided or different registered domains to the WC.

**Comment by lentzi90** [comment]
Yes that makes sense. If we use a separate domain for WC then it is all fine. :slightly_smiling_face: But this must be clear in the documentation then so an operator doesn't accidentally get into troubles. I could easily see someone set up multiple environments using the same registered domain, just different sub domains. One spammy user could then cause rate limits for *all* of them. :scream:
