### ISSUE TITLE
[3] Use individual credentials for admin access to Kubernetes API

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#323]
**Is your feature request related to a problem? Please describe.**
Cluster administrators should use individual credentials when accessing the Kubernetes API, instead of relying on a shared admin kubeconfig. Otherwise it is impossible to know who accessed the cluster.

**Describe the solution you'd like**
The necessary RBAC to grant all cluster admins access should be created as part of bootstrapping the cluster. After this the admin kubeconfig should not be used anymore for other than break glass situations. To ensure this, it would make sense to purge it from the local machine. In a break glass situation, it can simply be retrieved from the control-plane nodes.

In short:
1. Get admin kubeconfig
2. Install Dex
3. Create RBAC to bind cluster admins to the `cluster-admin` ClusterRole at the cluster level.
4. Generate a kubeconfig for individual access (see https://github.com/elastisys/compliantkubernetes-apps/issues/221 )
5. Purge the admin kubeconfig

**Describe alternatives you've considered**
An alternative would be to generate individual certificates and kubeconfigs for all admins using the CA used by the cluster [like this](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user). The certificates would need to be rotated every now and then and there is no way to revoke access without replacing all the certificates, so this solution would add a bit of operational overhead.

**Additional context**
This issues is in a way part of https://github.com/elastisys/ck8s/issues/50 and https://github.com/elastisys/ck8s/issues/442.
Note that Dex must be installed before we can switch to OIDC authentication, so it must be part of the bootstrap.
It may make sense to move the bootstrap to compliantkubernetes-kubespray and handle everything in this repository using OIDC auth. Since Dex becomes crucial for accessing the cluster with this change we should also add another replica to make it a bit more resilient.

**Definition of done:**
Cluster administrators use individual credentials when accessing Kubernetes API, for example by using OIDC authentication. Access to the shared admin kubeconfig should require ssh to the control-plane to retrieve it (so that the user is identified through ssh).

**Comment by viktor-f** [comment]
I think this sounds like a good plan. I'm not sure exactly when I want the dex installation to occur, apps vs kubespray, (we might want to apply it to ready kubernetes clusters and then it might make more sense for it to stay in ck8s-apps).
We will also need nginx so we can access dex.

**Comment by cristiklein** [comment]
We decided to take a "let's make the smells stand out" approach. Otherwise put "make it work, make it right, make it fast". This issue will focus on "make it work".

The overall approach will be as follows:

1. Create cluster using `compliantkubernetes-kubespray`; configure the OIDC provider to the to-be Dex endpoint.
2. Download KUBECONFIG with cluster-admin certificate.
3. Apply `compliantkubernetes-apps`
4. The above step installs `cluster-admin-rbac`.
5. Download KUBECONFIG with OpenID; wipe KUBECONFIG with cluster-admin certificate.
6. Re-apply `compliantkubernetes-apps` (just to test).

Unless I miss something, this issue is about (4) writing code/configuration/documentation for configuring `cluster-admin-rbac`, and (5) documenting a snippet to replace the KUBECONFIG in `.state`.

Once this issue is done, we will go back and "fix the smell", fully implementing [ADR-0007](https://compliantkubernetes.io/adr/0006-use-standard-kubeconfig-mechanisms/). We will need to consider not only the present OIDC issue, but also the (rather quirky) way to set up Compliant Kubernetes on top of managed vanilla Kubernetes services, like [OVH](https://compliantkubernetes.io/operator-manual/ovh-managed-kubernetes/) and [EKS-D](https://compliantkubernetes.io/operator-manual/eksd/).

**Comment by cristiklein** [comment]
Another idea:

We should be able to configure the Kubernetes apiserver *directly* with Google OpenID, without Dex. This would, of course, have the limitation that group claims would not work, but we don't really need them at this point.

So the procedure would look like:

1. Create a Google OpenID client ID and client secret. Make sure the callback URL allows `http://localhost:8080`.
2. Create the SC via `compliantkubernetes-kubespray` with Google OpenID client ID and client secret above.
3. Add a "known good" RBAC to allow cluster-admin to the people in the ops team. This can be done like `ssh ubuntu@$MASTER_IP sudo kubectl apply -f -`. I.e., no Kubernetes credentials are downloaded from the cluster.
4. Create a KUBECONFIG with an OpenID configuration, which uses directly the Google OpenID client ID and client secret.
5. Sops-encrypt the KUBECONFIG, save it in `.state` and apply `compliantkubernetes-apps` as usually.

We could proceed similarly with the WC, or point the WC to Dex running in SC.

If we go this way, we basically just need to add documentation for these steps.

**Comment by lentzi90** [comment]
> We should be able to configure the Kubernetes apiserver directly with Google OpenID, without Dex. This would, of course, have the limitation that group claims would not work, but we don't really need them at this point.

Good point, I had forgotten about this! It would probably be fine in many cases but there is of course the drawback that we then have 2 separate OIDC configurations. One for the API server and one of "everything else". To me the main reason to use dex is that we can configure everything through that one service and hide the various "backends". Kibana, Grafana, etc are always just configured the same in order to work with dex so we don't really have to think about it. It is also very nice to be able to add another backend or configure more static users and immediately have them work with Harbor, Grafana, Kibana as well as the API server.

I do see the value in this however, especially if we do it only for SC. Then users would still have the same experience since only operators use the SC API server.
