### ISSUE TITLE
[2] Upgrade to kubernetes v1.18

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#33]
With 1.20 coming up we should support 1.18

Maybe we already do. So this task will be to investigate what needs to be changed to support 1.18 and create new issues if there are any bigger changes that is needed.

Relevant info:
https://v1-18.docs.kubernetes.io/docs/setup/release/notes/

# Acceptance criteria

* Test to deploy onto a kubernetes 1.18 cluster
* Fix the things that doesn't work
* Create issues if there are any bigger changes needed

**Comment by Pradyumnakashyap** [comment]
As this involves testing and deployment of the ck8s cluster with the Kubernetes version v1.18.10, No PR for this issue is linked for closure, certain tests and results are mentioned below - 

1. The image used to test the upgrade on Exoscale was "ck8s-v1.18.10+ck8s0" (was already present), the only change with respect to code required for the upgrade is the replacement of the image in tfvars file.
2. Deployed the ck8s cluster with version 0.6 (Nodes having the above image and Kubernetes version v1.18.10):
                     - No issues with respect to API's or deprecation was noticed.
                     - ck8s cluster was deployed with all the apps and the automated tests were successful, only opendistro-es-curator 
                       pods were failing (which was expected behavior when compared to older Kubernetes versions)
3. Deployed the ck8s cluster with version 0.7 (Nodes having the above image and Kubernetes version v1.18.10):
                     - No Issues with respect to the API's or any deprecation was noticed.
                     - ck8s cluster deployed with all the apps and the automated tests were successful (which was expected behavior 
                       when compared to older Kubernetes versions).
                     - Some basic tests in the form of UI logins (Grafana and Kibana) and Harbor image push/pull image were 
                        successful.
                     - These tests were made with 'letsencrypt-prod' as value for both (wc|sc) config files to make sure Dex works.

**Note : To avoid warning for the Fluentd tolerations in the ck8s-version >= 0.7, I tried to update the 'node-role.kubernetes.io/master' and the 'value' component which passed the validation without warning but later error(ed) out. (keep the default settings with warnings)
