### ISSUE TITLE
[3] Convert daily checks into dashboards

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#373]
**Is your feature request related to a problem? Please describe.**

In the spirit of drinking our own Champagne and making our work more demonstrable, let's convert some of the daily checks into dashboards.

**Describe the solution you'd like**

Grafana dashboards that can be demonstrated by sales and are useful to ops. The ambition should be to eventually make daily scripts unnecessary. (They can still be around for troubleshooting.)

**Additional context**

For inspiration, see how the [Backup dashboard](https://compliantkubernetes.io/ciso-guide/backup/) allows us to prove to ourselves that backups are working.

Also, check how the [Capacity dashboard](https://compliantkubernetes.io/ciso-guide/kubernetes-status/) allows us to prove that all nodes / Pods are up.

**Definition of done:**

* Grafana dashboards to automate daily checks.
* Documentation for these daily checks on compliantkubernetes.io.

**Comment by lentzi90** [comment]
I'm interested in picking this up, but I'm not sure where to start. Most of the daily checks are for things like backups and disk usage, which can already be seen in the backups, Nodes or Persistent Volumes dashboards. (We even have alerts for most of these things, but not in older versions.) What's left is basically the things we don't have metrics for: S3 usage and InfluxDB shard sizes.

Daily tasks:

- ~~**Check InfluxDB backup**~~ This can be seen in the backup dashboard (but it only checks successful completion, not size in S3).
- **Check InfluxDB shard usage**
- **Check S3 quota usage**
- ~~**Check nodes disk usage**~~ This can be seen in the Nodes dashboard.
- (**Check deletion of old logs from SC in S3**) This is checked indirectly since we detect if the Job fails.
- ~~**Check Elasticsearch disk usage**~~ This can be seen in the Persistent Volumes dashboard.
- ~~**Check Elasticsearch snapshot**~~ This can be seen in the backup dashboard (successful completion of the Job).
- (**Verify that old Elasticsearch snapshot has been deleted**) Same as above. If the Job fails we will notice. This can be seen in Kibana and there seems to be some metrics that we could use to show it also in Grafana.

I could easily improve the current backup dashboard to show some more details for Elasticsearch snapshots. But for anything else a new exporter will be needed.

InfluxDB [doesn't expose metrics for shard size](https://github.com/influxdata/influxdb/issues/932) so we need to actually go into the Pod and check the size of the folder. This is basically something we would need to build and maintain.

There are a few exporters for S3 (not sure how well they work with S3 "compatible services") that we could try. They seem to provide generic information like number of objects and total size. This should be enough for keeping an eye on the quota and possibly a bit more (e.g. size and date of last modified object.

So what should we focus on? To me S3 and Elasticsearch makes most sense so I'll start looking into them. Happy for your thoughts. :slightly_smiling_face:

**Comment by OlleLarsson** [comment]
> InfluxDB doesn't expose metrics for shard size so we need to actually go into the Pod and check the size of the folder. This is basically something we would need to build and maintain.

Isn't this already exposed?
https://github.com/elastisys/influxdb-helm-charts/blob/elastisys_extensions/charts/influxdb/values.yaml#L18-L27

**Comment by cristiklein** [comment]
@lentzi90 I feel you are a better authority than me on this issue. Can you think about the following:

1. Should we put these into a "daily check" folder or dashboard to collect them into a single place?
2. Please go ahead with the lowest hanging fruit you suggested.

**Comment by tordsson** [comment]
@pettersv please chose how to prioritize this.
