### ISSUE TITLE
Intrusion detection dashboard shows wrong Pod

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#400]
**Describe the bug**

I have the feeling -- but I was wrong before -- that the Intrusion Detection / Falco dashboard uses the wrong label (see screenshot). Instead of labeling events by the misbehaving Pod, it labels events by the reporting Falco Pod.

If this is intended, please leave a comment and close the bug report.

**To Reproduce**
1. Install CK8s.
2. Install [Falco Event Generator](https://github.com/elastisys/ck-exoscale-config-ng/tree/master/user/falco-event-generator).
3. Look at the Intrusion Detection / Falco dashboard.

**Expected behavior**

I can see the name of the misbehaving Pod (e.g., `falco-event-generator-deployment-7bf5f7d76b-mrbcb`).

**Actual behavior**

I see the name of the reporting Pod (e.g., `falco-4xsfn`).

**Screenshots**

![Screenshot from 2021-04-21 21-30-03](https://user-images.githubusercontent.com/1660833/115610148-c1a72080-a2e8-11eb-8385-8f38f118cd50.png)

**Version (add all relevant versions):**
- Compliant Kubernetes apps v0.13.0

**Additional context**
Happens on the demo cluster.

**Comment by viktor-f** [comment]
Not sure what the intention is, but it sounds good to report the misbehaving pod instead of the reporting pod.
I did a quick check and the metrics do have labels for which pod in which namespace that is misbehaving, but only for some of the events (I guess some events might not be possible to trace to a pod or they originate from something else). So it should be pretty easy to fix, then you could also filter on namespaces.
