### ISSUE TITLE
Investigate/fix general fluentd issues

### ISSUE THREAD

**Issue by Ajarmar** [elastisys/compliantkubernetes-apps#576]
**Describe the bug**
Fluentd regularly has problems in various clusters, as well as in the pipeline.

- In clusters, the following error pops up:

```console
{"time":"2021-08-20 13:32:28 +0000","level":"warn","message":"[output-forwarding] failed to write data into buffer by buffer overflow action=:block","worker_id":0}
```

The error can usually be fixed by increasing the limits for the forwarders/aggregator until the Pods are ready, and then lowering the limits again.

- The pipeline fails somewhat often during the apps sc test due to fluentd not being ready. This may be due to the test being performed before the fluentd secret is ready.

**To Reproduce**
Not sure if it can be consistently reproduced.

**Expected behavior**
Fluentd runs without problems.

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version 0.17.0

**Additional context**

**Comment by aarnq** [comment]
In some instances the fluentd forwarder in the service cluster seem slow to respond to http health checks during startup. 
This is especially apparent on nodes generating more logs. It is probably due to the aggregator being the bottleneck, in turn filling up the buffers of the forwarder, and generating the error above.

As the http checks seem to slots in as parts of the logs which is ordered by time, this makes them delayed until everything before it has been processed. Combined, this makes the forwarder unable to respond until it has properly started up and caught up.

The fluentd chart provides limited configuration of liveness probe, however is does offer the possibility of sidecars which could perform a different liveness probe by checking the buffer directory for changes instead like [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml).

**Comment by aarnq** [comment]
I think this is fixed with the rework and exposure of the buffer config for the aggregator.

**Comment by OlleLarsson** [comment]
@aarnq close?
