### ISSUE TITLE
Investigate: Separate service cluster from workload cluster

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#62]
In order to achieve workload multi-tenancy (i.e., several workload clusters, one service cluster) and simplify setting up Compliant Kubernetes cluster, it should be possible to completely set up a service cluster without knowing anything about the workload cluster. Currently, the service cluster pushes metrics from the workload cluster.

This tasks consists in identifying all blockers to making the service cluster independent from the workload cluster.

Acceptance criteria:
- We know all references to the workload cluster from the service cluster.
- We identified what needs to be done to make the service cluster independent.
- We maintain the status of "tamper-proof logging environment" of the service cluster.

**Comment by tordsson** [comment]
Prometheus is the only dependency going the other direction. 
Migration to Thanos/Cortex could be a solution, or writing metrics directly to Prometheus backend (currently Influx)

**Comment by tordsson** [comment]
From duplicate issue, merge...

Acceptance criteria:

Can create a new workload cluster and connect that with an existing service cluster
Can have more than one workload cluster sharing the same service cluster.
No hard multi-user multi-tenancy, but assume that the same identity provider is used for all clusters.
part of elastisys/compliantkubernetes-apps#58

Some considerations for cluster creation:

Current installation pair-oriented (always creates two clusters)
Need CLI updates, there are assumptions about paired configs, init runs twice, etc.
Any pairwise naming dependencies (service lookup by name pairing…)?
Need to be able to connect to existing service cluster (instead of creating one as part of workload cluster install)
Likely, more such dependencies in the apps repo than the cluster one

**Comment by tordsson** [comment]
Let's go with the alternative of exposing InfluxDB (for append-only usage for workload cluster) to the workload cluster.
