### ISSUE TITLE
[3] Remove wc-reader-prometheus

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#784]
**Is your feature request related to a problem? Please describe.**

Since we would like to remove wc-reader-prometheus we somehow need to get wc alerts somehow. One solution would be to use the rule component and send alerts to our current alertmanager. Another solution would be to setup an ops alertmanager in wc.

Investigate a little bit and see what's the best option. Take at least this into consideration https://thanos.io/v0.24/components/rule.md/#risk

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
When could this feature be considered done.

* WC-reader-prometheus is gone
* wc alerts are going to ops alertmanager

**Comment by aarnq** [comment]
I've looked through this a bit and is this something we want to discuss and decide on in the team or do we proceed with the option that seems like the better and more manageable option?

Currently that looks to be Thanos Ruler, since we'd be able to manage all our alert rules through it and have more of a herd attitude for wc alerting. Since the Thanos Receivers store data locally the would be evaluated in the cluster which shouldn't make query reliability too much of a concern.
Of course this setup would still include alert rules in Prometheus to monitor Thanos, especially Thanos Ruler, so if it would become an issue we would know.
