### ISSUE TITLE
[2] pods - check if default resource limits and requests are still valid

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#832]
**What should be investigated.**
Do we need to update our resources limits and requests?
Check on live cluster and see where we should take actions.

**Definition of Done**
1. the the current usage of pods in various live cluster
2. propose some new limits and requests
3. do we need to update our standard cluster sizing (take into consideration removal of influxdb and adding thanos)

**Comment by lucianvlad** [comment]
results of investigation are in PR https://github.com/elastisys/ck8s-ops/pull/1928

**Comment by lucianvlad** [comment]
Results of the investigation can be viewed in this google sheet [file](https://docs.google.com/spreadsheets/d/1-5bhtg8dWKnBpTT0CdmweaTOLXjnMX5If9wDrQqo8jc/edit#gid=0)
I have highlighted with yellow the pods that are using more memory then allocated in requests and with pink the pods that are CPU throttled more then 25%.

I have extracted a list of common pods that are using more memory then requests :
===============================================================================================
cluster	    		   pod				    								requests	    			limits	    		   ussage
wc/sc			metrics-server  									25						100					33
wc/sc			calico-node											61.04					217					155
WC				dns-autoscaler										10						-					14
SC/WC			etcd												100						-					334
WC				prometheus-kube-prometheus-stack-prometheus-0		1024					3072				1832
SC/WC			cert-manager-cain-injector							100						250					125
SC				fluentd												300						572					475
SC				fluentd-0											300						1000				492

As we can see all the pods that are using more memory then the assigned requests have a higher value for limits and because of that we are OK.
I would say that for now we are OK with what is allocated for memory requests and limits and that if we want to change anything we will need to change some node memory sizes.

**Comment by lucianvlad** [comment]
results of investigation are in PR https://github.com/elastisys/ck8s-ops/pull/1928
