### ISSUE TITLE
[2] Kibana/opensearch dashboards- 401, error Unauthorized

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#900]
**Describe the bug**
Opensearch Dashboards/Kibana sometimes enters a bad state with message

```
{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
```

My guess is that this happens 
1. because dex is not available when kibana starts
2. or dex is terminated while kibana/osd is running that that meeses with things.

My guess is on (1).

**To Reproduce**

**Expected behavior**
Kibana/osd is always accessible when it is running

**Screenshots**
![image](https://user-images.githubusercontent.com/12396964/158793488-01d574d9-afbf-4423-9ee8-618836943187.png)

**Version (add all relevant versions):**
All version with kibana/osd

**Additional context**

**Comment by cristiklein** [comment]
I see two options:

1. Make the OSD startup process fail, so that it retries and eventually succeeds.
2. Move OpenSearch one layer "above" in Helmfile, e.g., `55-applications-needing-openid.yaml`.

Given that many processes want to check out the `.well-known/openid-configuration` endpoint exposed by Dex, (2) makes most sense to me.

In the future, if required, we could even move Harbor and Grafana in layer 55.
